In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = A+B

print("Matrix A:")
print (A)

print("Matrix B:")
print(B)

print("Addition of matrices:")
print(C)


Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8  9]
 [10 11 12]]
Addition of matrices:
[[ 8 10 12]
 [14 16 18]]


In [3]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = A-B

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Subtraction of matrices:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8  9]
 [10 11 12]]
Subtraction of matrices:
[[-6 -6 -6]
 [-6 -6 -6]]


In [4]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = A*B
print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Multiplication of matrices:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8  9]
 [10 11 12]]
Multiplication of matrices:
[[ 7 16 27]
 [40 55 72]]


In [5]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = A/B

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Division of matrices:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8  9]
 [10 11 12]]
Division of matrices:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
