In [2]:
import numpy as np
A = np.array([[40,50],[90,80]])
B = np.array([[60,70],[20,10]])

while True:
    print("Array")
    print("1.Addition")
    print("2.Subtraction")
    print("3.Multiplication")
    print("4.Division")
    print("5.Exit")

    choice = int(input("Enter your choice:"))

    if choice ==1:
        print("Addition")
        print(A+B)

    elif choice ==2:
        print("Subtraction")
        print(A-B)

    elif choice ==3:
        print("Multiplication")
        print(A*B)

    elif choice ==4:
        print("Division")
        print(A/B)

    elif choice ==5:
        print("Program ended")
        break

    else:
        print("Invalid choice!")

Array
1.Addition
2.Subtraction
3.Multiplication
4.Division
5.Exit


Enter your choice: 2


Subtraction
[[-20 -20]
 [ 70  70]]
Array
1.Addition
2.Subtraction
3.Multiplication
4.Division
5.Exit


Enter your choice: 1


Addition
[[100 120]
 [110  90]]
Array
1.Addition
2.Subtraction
3.Multiplication
4.Division
5.Exit


Enter your choice: 3


Multiplication
[[2400 3500]
 [1800  800]]
Array
1.Addition
2.Subtraction
3.Multiplication
4.Division
5.Exit


Enter your choice: 4


Division
[[0.66666667 0.71428571]
 [4.5        8.        ]]
Array
1.Addition
2.Subtraction
3.Multiplication
4.Division
5.Exit


Enter your choice: 5


Program ended
